// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

// prettier-ignore
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";

export type Player = { name: string }

export type Team = { name: string; players: Player[]; division: string | null; exhibition: boolean; manual_rank: number }

export type PlayerScore = { player_index: number; gp: number; q: [number, number, number, number]; points: number }

export type TeamScore = { team_index: number; total_points: number; bonus_heard: number; bonus_points: number; bb_heard: number; bb_points: number; ot_gets: number; lightning_points: number; player_scores: (PlayerScore | null)[] }

export type Game = { game_index: string; round: number; team_a: TeamScore; team_b: TeamScore; tossups_heard: number; overtime: boolean; forfeit: boolean }

export type ScoringSettings = { q_values: [number, number, number, number]; q_enabled: [boolean, boolean, boolean, boolean]; track_power_neg: boolean; track_light_round: boolean; track_tuh: boolean; auto_track: number; sort_by_ppg: boolean }

export type ReportSettings = { base_name: string; rounds: string; standings: string; individuals: string; games: string; team_detail: string; player_detail: string; stat_key: string; style: string; include_rounds: boolean; include_standings: boolean; include_individuals: boolean; include_games: boolean; include_team_detail: boolean; include_player_detail: boolean; include_stat_key: boolean; use_style_sheet: boolean; british_style: boolean }

export type Tournament = { name: string; teams: Team[]; games: Game[]; scoring: ScoringSettings; reports: ReportSettings; uses_divisions: boolean; divisions: string[]; track_bonuses: boolean; max_players_per_team: number; sort_method: number; warn_flags: number; packets: Record<number, string> }

export const commands = {
    async getTournament(): Promise<Tournament> {
        return await TAURI_INVOKE("get_tournament");
    },
    async newTournament(): Promise<Tournament> {
        return await TAURI_INVOKE("new_tournament");
    },
    async openFile(path: string): Promise<Tournament> {
        return await TAURI_INVOKE("open_file", { path });
    },
    async saveFile(path: string): Promise<Tournament> {
        return await TAURI_INVOKE("save_file", { path });
    },
    async updateTournament(tournament: Tournament): Promise<Tournament> {
        return await TAURI_INVOKE("update_tournament", { tournament });
    },
    async getFilePath(): Promise<string | null> {
        return await TAURI_INVOKE("get_file_path");
    },
    async generateReports(dir: string): Promise<string[]> {
        return await TAURI_INVOKE("generate_reports", { dir });
    },
    async findDuplicateGames(): Promise<number[]> {
        return await TAURI_INVOKE("find_duplicate_games");
    },
    async checkNameCapitalization(name: string): Promise<boolean> {
        return await TAURI_INVOKE("check_name_capitalization", { name });
    },
    async openInBrowser(path: string): Promise<void> {
        return await TAURI_INVOKE("open_in_browser", { path });
    },
}
